version: '3'

services:
  frontend-container:
    build: ./../business-loan-app
    networks:
      - default-network
    ports:
      - '8888:80'

  backend-container:
    build: .
    networks:
      - default-network

networks:
  default-network:
